Support types that require Quoting
supabase/walrus pull request #41
Opened 2022-02-15 18:24 UTC by olirice

## What kind of change does this PR introduce?
Fixes a bug where the text representation of types are incorrectly cast to regtype, resulting in runtime exceptions, when the type requires quotes `"`

## What is the current behavior?
Processing a WAL record containing a custom quoted type e.g.
```sql
create type "MyType" as enum('1');

create table xyz(
    id serial primary key,
    x "MyType"
);

insert into xyz(x) values ( '1');
```
results in an error
```sql
message: "type \"mytype\" does not exist"
```

Due to [this](https://github.com/supabase/walrus/compare/cast_regtype?expand=1#diff-bd85ab1223dc61b5379444cf8fbeb7dcaf3c0dc2343a6a6be069ff71ed036ccfL256) approach to casting

## What is the new behavior?
Quoted types can be cast to regclass via [this function](https://github.com/supabase/walrus/compare/cast_regtype?expand=1#diff-bd85ab1223dc61b5379444cf8fbeb7dcaf3c0dc2343a6a6be069ff71ed036ccfR16)

## A Better Fix (Future)
wal2json has a setting called `include-type-oids` that is much easier to work with because it does not require quoting.  Currently, that option is not compatible with `format-version=2`, which is what we use. I [opened an issue at wal2json](https://github.com/eulerto/wal2json/issues/232) asking for it to be ported. If that issue gets traction, we should use the oids instead

2022-02-16 04:39 UTC, w3b6x9 requested changes
@olirice i spun up a brand new database, applied the new changes, and tried:

```sql
create type "MyType" as enum('1');

create table xyz(
    id serial primary key,
    x "MyType"
);

insert into xyz(x) values ( '1');
```

and i got:

```sql
ERROR:  invalid input syntax for type json
DETAIL:  Token "MyType" is invalid.
CONTEXT:  JSON data, line 1: ...:"integer","value":1},{"name":"x","type":""MyType...
```

so i'm still getting the error this PR is supposed to address.

2022-02-16 13:01 UTC, olirice commented
The error 
```sql
-- note the double quotes around ""MyType""
CONTEXT:  JSON data, line 1: ...:"integer","value":1},{"name":"x","type":""MyType...
```
is showing "MyType" as double quoted and capitalized so that looks like the wal2json < 2.4 issue.

The regression issue that this PR is for would show `"mytype" does not exist`

I think you may have an outdated version of the `supabase/postgres` image used in `docker-compose.yml`

Try
```sh
docker-compose down -v
docker pull supabase/postgres
docker-compose up
``` 

Then, connect to that database and then you can use the attached SQL script to set up for manual testing. It includes some sample outputs but feel free to change things up to try to break it. Expected output shown below.

[walrus_manual_test.txt](https://github.com/supabase/walrus/files/8080010/walrus_manual_test.txt)

| is_rls_enabled | subscription_ids | errors | wal |
---------------|------------------|--------|-----|
| false |	"{607dbf0b-80f4-4892-80ae-c8bc58da817d}"|	"{}"	|"{""type"": ""INSERT"", ""table"": ""xyz"", ""record"": {""x"": ""1"", ""id"": 1}, ""schema"": ""public"", ""columns"": [{""name"": ""id"", ""type"": ""int4""}, {""name"": ""x"", ""type"": ""MyType""}], ""commit_timestamp"": ""2022-02-16T12:41:08Z""}" |
| false | "{607dbf0b-80f4-4892-80ae-c8bc58da817d}" | "{}" |	"{""type"": ""UPDATE"", ""table"": ""xyz"", ""record"": {""x"": ""1"", ""id"": 1}, ""schema"": ""public"", ""columns"": [{""name"": ""id"", ""type"": ""int4""}, {""name"": ""x"", ""type"": ""MyType""}], ""old_record"": {""id"": 1}, ""commit_timestamp"": ""2022-02-16T12:41:08Z""}" |
| false|	"{607dbf0b-80f4-4892-80ae-c8bc58da817d}"	|"{}"|	"{""type"": ""DELETE"", ""table"": ""xyz"", ""schema"": ""public"", ""columns"": [{""name"": ""id"", ""type"": ""int4""}, {""name"": ""x"", ""type"": ""MyType""}], ""old_record"": {""id"": 1}, ""commit_timestamp"": ""2022-02-16T12:41:08Z""}"|

2022-02-17 00:48 UTC, w3b6x9 commented
@olirice ah yes, sounds like it! let me upgrade and try it again.

2022-02-17 04:12 UTC, w3b6x9 commented
> The error
> 
> ```sql
> -- note the double quotes around ""MyType""
> CONTEXT:  JSON data, line 1: ...:"integer","value":1},{"name":"x","type":""MyType...
> ```
> 
> is showing "MyType" as double quoted and capitalized so that looks like the wal2json < 2.4 issue.
> 
> The regression issue that this PR is for would show `"mytype" does not exist`
> 
> I think you may have an outdated version of the `supabase/postgres` image used in `docker-compose.yml`
> 
> Try
> 
> ```shell
> docker-compose down -v
> docker pull supabase/postgres
> docker-compose up
> ```
> 
> Then, connect to that database and then you can use the attached SQL script to set up for manual testing. It includes some sample outputs but feel free to change things up to try to break it. Expected output shown below.
> 
> [walrus_manual_test.txt](https://github.com/supabase/walrus/files/8080010/walrus_manual_test.txt)
> 
> is_rls_enabled	subscription_ids	errors	wal
> false	"{607dbf0b-80f4-4892-80ae-c8bc58da817d}"	"{}"	"{""type"": ""INSERT"", ""table"": ""xyz"", ""record"": {""x"": ""1"", ""id"": 1}, ""schema"": ""public"", ""columns"": [{""name"": ""id"", ""type"": ""int4""}, {""name"": ""x"", ""type"": ""MyType""}], ""commit_timestamp"": ""2022-02-16T12:41:08Z""}"
> false	"{607dbf0b-80f4-4892-80ae-c8bc58da817d}"	"{}"	"{""type"": ""UPDATE"", ""table"": ""xyz"", ""record"": {""x"": ""1"", ""id"": 1}, ""schema"": ""public"", ""columns"": [{""name"": ""id"", ""type"": ""int4""}, {""name"": ""x"", ""type"": ""MyType""}], ""old_record"": {""id"": 1}, ""commit_timestamp"": ""2022-02-16T12:41:08Z""}"
> false	"{607dbf0b-80f4-4892-80ae-c8bc58da817d}"	"{}"	"{""type"": ""DELETE"", ""table"": ""xyz"", ""schema"": ""public"", ""columns"": [{""name"": ""id"", ""type"": ""int4""}, {""name"": ""x"", ""type"": ""MyType""}], ""old_record"": {""id"": 1}, ""commit_timestamp"": ""2022-02-16T12:41:08Z""}"

@olirice alright so i was able to reproduce this.

however, when i run the other query for the pub:

```sql
with pub as (
    select
        concat_ws(
            ',',
            case when bool_or(pubinsert) then 'insert' else null end,
            case when bool_or(pubupdate) then 'update' else null end,
            case when bool_or(pubdelete) then 'delete' else null end
        ) as w2j_actions,
        coalesce(
            string_agg(
                realtime.quote_wal2json(format('%I.%I', schemaname, tablename)::regclass),
                ','
            ) filter (where ppt.tablename is not null),
            ''
        ) w2j_add_tables
    from
        pg_publication pp
        left join pg_publication_tables ppt
            on pp.pubname = ppt.pubname
    where
        pp.pubname = 'supabase_realtime'
    group by
        pp.pubname
    limit 1
),
w2j as (
    select
        x.*, pub.w2j_add_tables
    from
         pub,
         pg_logical_slot_get_changes(
            'realtime', null, null,
            'include-pk', '1',
            'include-transaction', 'false',
            'include-timestamp', 'true',
            'write-in-chunks', 'true',
            'format-version', '2',
            'actions', pub.w2j_actions,
            'add-tables', pub.w2j_add_tables
        ) x
)
select
    xyz.wal,
    xyz.is_rls_enabled,
    xyz.subscription_ids,
    xyz.errors
from
    w2j,
    realtime.apply_rls(
        wal := w2j.data::jsonb,
        max_record_bytes := 1048576
    ) xyz(wal, is_rls_enabled, subscription_ids, errors)
where
    w2j.w2j_add_tables <> ''
    and xyz.subscription_ids[1] is not null;
```

i get the following error:

```sql
ERROR:  type "realtime.user_defined_filter[]" does not exist
CONTEXT:  SQL function "parse_regtype" statement 1
PL/pgSQL assignment "columns =
        array_agg(
            (
                x->>'name',
                x->>'type',
                realtime.cast(
                    (x->'value') #>> '{}',
                    realtime.parse_regtype((x->>'type'))
                ),
                (pks ->> 'name') is not null,
                true
            )::realtime.wal_column
        )
        from
            jsonb_array_elements(wal -> 'columns') x
            left join jsonb_array_elements(wal -> 'pk') pks
                on (x ->> 'name') = (pks ->> 'name')"
PL/pgSQL function realtime.apply_rls(jsonb,integer) line 51 at assignment
```

2022-02-18 16:44 UTC, olirice commented
Ok, was able to reproduce that error

```
PL/pgSQL function realtime.apply_rls(jsonb,integer) line 51 at assignment
```

It was happening because the publication `supabase_realtime` was set to track all tables INCLUDING `realtime.*`. 
Since the `authenticated` user does not have access to the `realtime` schema (or its types), it threw an error.

We did not hit this error in the sample sql file i sent because of this wal2json setting:
```
        'filter-tables', 'realtime.*'
```

The easiest way to resolve it is to reverse the order of 

```
-- Create the slot
select * from pg_create_logical_replication_slot('realtime', 'wal2json', false)

--- Subscribe to the table (no records returned without this)
insert into realtime.subscription(subscription_id, entity, claims)
select extensions.uuid_generate_v4(), 'xyz', '{"
role": "authenticated"}';
```

so the WAL record for inserting into the `realtime.subscription` table is not part of the result set.

The attached manual testing file has that change + uses the publication query.

The test suite also uses the full query w/ publications so its definitely a permissions thing that doesn't apply in prod.

[walrus_manual_test.txt](https://github.com/supabase/walrus/files/8098859/walrus_manual_test.txt)

2022-02-18 23:50 UTC, w3b6x9 approved these changes
lgtm!

2022-02-19 00:16 UTC, w3b6x9 requested changes
@olirice hmm so i'm trying this out in Realtime RLS and i still see `"type \"realtime.user_defined_filter[]\" does not exist"`. in production there are cases where role is `authenticated` and all tables are listened to so wouldn't this come up again?

2022-02-19 13:10 UTC, olirice commented
> @olirice hmm so i'm trying this out in Realtime RLS and i still see `"type \"realtime.user_defined_filter[]\" does not exist"`. in production there are cases where role is `authenticated` and all tables are listened to so wouldn't this come up again?

good point. opened issue #42 b/c its independent from this change. will get that knocked out in another PR

2022-02-19 13:12 UTC, olirice commented
FYI I really don't like the fix introduced in the PR (pattern matching on string)

Since its a low impact bug w/ an existing work-around I'm going to let it hang out here for a week or two in hopes we get better suggestion from the linked wal2json issue. Lmk if you feel differently and I'll merge

2022-02-20 01:35 UTC, w3b6x9 approved these changes
sounds good on leaving it open for a couple of days. i'm going to approve in case you want to merge it in. i'll hold off on integrating into realtime for now.

2022-02-22 16:43 UTC, olirice commented
Closing b/c this is a bad implementation of a worse idea

2022-02-22 16:43 UTC, closed without merging